version: '3.8'

name: ollama-flowise-setup

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: sh
    command: -c "ollama serve"

  flowise:
    image: flowiseai/flowise
    container_name: flowise
    ports:
      - "3000:3000"
    environment:
      - FLOWISE_USERNAME=admin
      - FLOWISE_PASSWORD=admin
      - PORT=3000
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
